import pygame

pygame.init()
info = pygame.display.Info()

# BOARD SIZE
BOARD_ROWS = 10
BOARD_COLS = 9


PANEL_WIDTH = 300
BOARD_AREA_WIDTH = 800

FULLSCREEN = False
SCREEN_WIDTH = BOARD_AREA_WIDTH + PANEL_WIDTH
SCREEN_HEIGHT = 900
FPS = 60
CELL_SIZE = 70
BOARD_OFFSET_X = 60
BOARD_OFFSET_Y = 120


# PLAYER / COLOR SIDE
RED = 1
BLACK = -1
EMPTY = 0

# PIECE TYPES
KING = "K"
ADVISOR = "A"
ELEPHANT = "B"
ROOK = "R"
KNIGHT = "N"
CANNON = "C"
PAWN = "P"

# PIECE VALUES FOR AI
PIECE_VALUES = {
    KING: 10000,
    ROOK: 500,
    KNIGHT: 300,
    CANNON: 300,
    ADVISOR: 200,
    ELEPHANT: 200,
    PAWN: 100,
}

# UI COLORS
WHITE = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)
RED_COLOR = (220, 20, 60)
BEIGE = (240, 217, 181)

PANEL_BG = (230, 220, 200)
TEXT_COLOR = (30, 30, 30)
WIN_COLOR = (200, 30, 30)

PALACE_COLS = range(3, 6)
RED_PALACE_ROWS = range(7, 10)
BLACK_PALACE_ROWS = range(0, 3)

RED_FORWARD = -1
BLACK_FORWARD = 1

SELECT_COLOR = (255, 215, 0)
VALID_MOVE_COLOR = (0, 180, 0)
MOVE_HINT_RING = (40, 150, 40)
MOVE_HINT_RING = (40, 150, 40)

ONGOING = 0
DRAW = 2
RED_WIN = 1
BLACK_WIN = -1

# BUTTONS
BUTTON_WIDTH = 180
BUTTON_HEIGHT = 48
BUTTON_RADIUS = 10

UNDO_BUTTON_Y = 430
RESET_BUTTON_Y = 495
PAUSE_BUTTON_Y = 560
MENU_BUTTON_Y = 625

BUTTON_BG = (70, 120, 220)
BUTTON_BG_2 = (60, 170, 90)
BUTTON_BG_3 = (220, 140, 60)
BUTTON_BG_4 = (170, 80, 80)
BUTTON_TEXT_COLOR = (255, 255, 255)

OVERLAY_COLOR = (0, 0, 0, 100)

ASSET_FOLDER = "assets/images/"

RED_PIECE_IMAGES = {
    KING: ASSET_FOLDER + "red_king.png",
    ROOK: ASSET_FOLDER + "red_rook.png",
    KNIGHT: ASSET_FOLDER + "red_knight.png",
    CANNON: ASSET_FOLDER + "red_cannon.png",
    ADVISOR: ASSET_FOLDER + "red_advisor.png",
    ELEPHANT: ASSET_FOLDER + "red_elephant.png",
    PAWN: ASSET_FOLDER + "red_pawn.png",
}

BLACK_PIECE_IMAGES = {
    KING: ASSET_FOLDER + "black_king.png",
    ROOK: ASSET_FOLDER + "black_rook.png",
    KNIGHT: ASSET_FOLDER + "black_knight.png",
    CANNON: ASSET_FOLDER + "black_cannon.png",
    ADVISOR: ASSET_FOLDER + "black_advisor.png",
    ELEPHANT: ASSET_FOLDER + "black_elephant.png",
    PAWN: ASSET_FOLDER + "black_pawn.png",
}

# APP STATES
MENU_STATE = "menu"
MODE_SELECT_STATE = "mode_select"
AI_BATTLE_SELECT_STATE = "ai_battle_select"
PLAYING_STATE = "playing"

# GAME MODES
PVP_MODE = "pvp"
PVAI_MODE = "pvai"
AIVAI_MODE = "aivai"

# AI ALGORITHMS
AI_MINIMAX = "Minimax"
AI_ALPHABETA = "Alpha-Beta"

# DIFFICULTY
DIFFICULTY_LEVELS = {
    "Easy": 2,
    "Medium": 3,
    "Hard": 4,
}

# ANIMATION
MOVE_ANIMATION_DURATION = 0.18  # seconds
AI_MOVE_DELAY = 180  # milliseconds