import pygame

pygame.init()
info = pygame.display.Info()

# BOARD SIZE
BOARD_ROWS = 10
BOARD_COLS = 9

# SCREEN SETTINGS
FULLSCREEN = False
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 900
FPS = 60

CELL_SIZE = 70
BOARD_OFFSET_X = (SCREEN_WIDTH - (BOARD_COLS - 1) * CELL_SIZE) // 2
BOARD_OFFSET_Y = (SCREEN_HEIGHT - (BOARD_ROWS - 1) * CELL_SIZE) // 2

# PLAYER / COLOR SIDE
RED = 1
BLACK = -1
EMPTY = 0

# PIECE TYPES
KING = "K"
ADVISOR = "A"
ELEPHANT = "B"
ROOK = "R"
KNIGHT = "N"
CANNON = "C"
PAWN = "P"

# PIECE VALUES FOR AI
PIECE_VALUES = {
    KING: 10000,
    ROOK: 500,
    KNIGHT: 300,
    CANNON: 300,
    ADVISOR: 200,
    ELEPHANT: 200,
    PAWN: 100,
}

# UI COLORS
WHITE = (255, 255, 255)
BLACK_COLOR = (0, 0, 0)
RED_COLOR = (220, 20, 60)
BEIGE = (240, 217, 181)

PALACE_COLS = range(3, 6)

RED_PALACE_ROWS = range(7, 10)
BLACK_PALACE_ROWS = range(0, 3)

RED_FORWARD = -1
BLACK_FORWARD = 1